@startuml

hide members

rectangle "Application\nDeveloper" as User #lightgreen {

}

package "Services" as Used #lightgreen {

}
package "Workloads" as Used2 #lightgreen {

}
rectangle "Consumer" #lightgray {

}
rectangle "Data Sources" #lightgray {

}
package "Application/Analytics" #lightblue {

    interface "Application/Analytics" {
    }

    CLI ()-- "Application/Analytics"
    REST ()-- "Application/Analytics"
    Web ()-- "Application/Analytics"
    class Ingress << (S,orange) >>
    class Annotation << (S, orange) >>
    class Analytics  << (S, orange) >>
    class Storage << (S, orange) >>
    class Training << (S, orange) >>
    class Inference << (S, orange) >>
    class Streaming << (S, orange) >>
    class Egress << (S, orange) >>

    Ingress -> Annotation
    Ingress --> Streaming
    Streaming -> Egress
    Annotation -> Analytics
    Analytics -> Storage
    Storage -> Egress
    Storage --> Training
    Training --> Inference
    Inference -> Egress

}

User -> "Application/Analytics"
"Application/Analytics" --> Used
"Application/Analytics" --> Used2
Egress --> Consumer
"Data Sources" --> Ingress

@enduml
