@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Control/Data Coordinator/Data Movement" #lightblue {

    interface "Control/Data Coordinator/Data Movement" {
    }

    CLI ()-- "Control/Data Coordinator/Data Movement"
    REST ()-- "Control/Data Coordinator/Data Movement"
    Web ()-- "Control/Data Coordinator/Data Movement"
}

User --> "Control/Data Coordinator/Data Movement"
"Control/Data Coordinator/Data Movement" --> Used

@enduml
