@startuml
rectangle "Diagram TBD"
@enduml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Telemetry/Telemetry Subscriber" #lightblue {

    interface "Telemetry/Telemetry Subscriber" {
    }

    CLI ()-- "Telemetry/Telemetry Subscriber"
    REST ()-- "Telemetry/Telemetry Subscriber"
    Web ()-- "Telemetry/Telemetry Subscriber"
}

User --> "Telemetry/Telemetry Subscriber"
"Telemetry/Telemetry Subscriber" --> Used


