@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Telemetry/Telemetry Bus" #lightblue {

    interface "Telemetry/Telemetry Bus" {
    }

    CLI ()-- "Telemetry/Telemetry Bus"
    REST ()-- "Telemetry/Telemetry Bus"
    Web ()-- "Telemetry/Telemetry Bus"
}

User --> "Telemetry/Telemetry Bus"
"Telemetry/Telemetry Bus" --> Used

@enduml
