@startuml

package Edgeville #lightgray {
    rectangle "Cloud Layer" as Cloud #pink {
      rectangle "SDI"
      rectangle "uSDI"
      rectangle "Multi\nCloud" as HC
      HC --> "n" SDI
      HC --> "n" uSDI
    }
    rectangle "Control Layer" as Control #lightgreen {
      rectangle "Data\nCoordinator" as DC
      rectangle "Edgeville Manager" as EM
      rectangle "Edgeville Agent" as EA
      rectangle "Telemetry" as Telemetry
      rectangle "Security" as Security
      EM "1" *--> "n" EA
      EM --> DC
      EM -> Telemetry
      EA -> Telemetry
      EM --> Security
      EA --> Security
    }
    rectangle "Application Layer" as AL #lightblue {
      rectangle "Analytics" as ALA
      rectangle "Event Driven Workload" as ALE
      rectangle "Procedural Driven Workload" as ALP
      rectangle "Workload Automation" as ALW
      ALA --> ALP
      ALA --> ALE
      ALE --> ALW
      ALP --> ALW
    }
    rectangle "Physical Layer" as PL #plum {
      rectangle "Data Center" as PLDC
      rectangle "Aggregated\nEdge Device" as AED
      rectangle "Edge Device" as ED
      rectangle "End Point" as EP
      rectangle "IOT Gateway" as IG
      PLDC "1" *-> "n" AED
      PLDC "1" *--> "n" ED
      AED "1" *-> "n" ED
      AED "1" *--> "n" IG
      AED "1" *--> "n" EP
      ED "1" *-> "n" IG
      IG "1" *-> "n" EP
      ED "1" *--> "n" EP
    }

    AL ----> Cloud : runs on
    Cloud ---> Control
    Control ----> PL
}
@enduml


