@startuml
package "Common Cloud Core" as HC #pink {
  rectangle "Portal" {
  }
  database "Registry" {
  }
  rectangle "Control" {
  }
  rectangle "Service\nOrchestrator" as SO {
  }
  Portal --> SO
  SO --> Control
  SO -> Registry
  Registry --> Control
}
package "SDI" #lightblue {
  rectangle "Orchestrator" as OSDI {
  }
  rectangle "Storage" as SSDI {
  }
  rectangle "Compute" as CSDI {
  }
  rectangle "Network" as NSDI {
  }
  OSDI --> SSDI
  OSDI --> CSDI
  OSDI --> NSDI
}
package "uSDI" #lightgreen {
      rectangle "Orchestrator" as OuSDI {
      }
      rectangle "Storage" as SuSDI {
      }
      rectangle "Compute" as CuSDI {
      }
      rectangle "Network" as NuSDI {
      }
      OuSDI --> SuSDI
      OuSDI --> CuSDI
      OuSDI --> NuSDI
}

Control --> OuSDI
Control --> OSDI
@enduml

