@startuml
rectangle "Diagram TBD"
@enduml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Security/Remediation" #lightblue {

    interface "Security/Remediation" {
    }

    CLI ()-- "Security/Remediation"
    REST ()-- "Security/Remediation"
    Web ()-- "Security/Remediation"
}

User --> "Security/Remediation"
"Security/Remediation" --> Used


