@startuml

package "Cloud" as User #ffffcc {

}

package "Physical Layer" as Used #ffffcc {

}

package "Data Coordinator" #lightblue {

    interface "Data Coordinator" as DC {
    }

    CLI ()-- DC
    REST ()-- DC
    Web ()-- DC
    package "Data Exchange" as DE #white {
    }
    package "Data Movement" as DM #white {
    }
    package "Application Movement" as AM #white {
    }
    package "Meta-Data Management" as MDM #white {
    }
    DC --> DE
    DC --> DM
    DC --> AM
    DC --> MDM

}

User --> DC
DE --> Used
DM --> Used
AM --> Used
MDM --> Used

@enduml
