@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Analytics" #lightblue {

    interface "Analytics" {
    }

    CLI ()-- "Analytics"
    REST ()-- "Analytics"
    Web ()-- "Analytics"
}

User --> "Analytics"
"Analytics" --> Used

@enduml
