@startuml

left to right direction

actor :User: as User
actor :IOT Device: as device


rectangle "Analytics" #lightBlue {
    UseCase UC1 as "Analyze Data\nFrom Edge"
    UseCase UC2 as "Analyze Data\nIn Edge"
    UseCase UC3 as "Collect Data"
    UseCase UC4 as "Perform Action"
    UseCase UC5 as "Perform Action\nIn Edge"
    UseCase UC6 as "Generate Report"
    UseCase UC7 as "Define Analytics\nApplication"
}

rectangle "Control" #lightgreen {
  UseCase UC10 as "Deploy Application\nIn Data Center"
  UseCase UC11 as "Deploy Application\nIn Edge"
}

UC3 ---> device
UC3 -> UC2
UC2 --> UC1
UC1 -> UC4
UC4 --> UC5
User -> UC6
User -> UC7
UC4 --> UC6
UC7 ..> UC3
UC7 ..> UC1
UC7 ..> UC2
UC7 ..> UC4
UC7 ..> UC5

UC7 --> UC10
UC7 --> UC11

@enduml
