@startuml
rectangle "Diagram TBD"
@enduml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Cloud/SDI" #lightblue {

    interface "Cloud/SDI" {
    }

    CLI ()-- "Cloud/SDI"
    REST ()-- "Cloud/SDI"
    Web ()-- "Cloud/SDI"
}

User --> "Cloud/SDI"
"Cloud/SDI" --> Used


