@startuml

hide member

package "Application" #lightblue {

    interface "Application" as APPI {
    }

    CLI ()-- "APPI"
    REST ()-- "APPI"
    Web ()-- "APPI"
    package "Workloads" as W #ffffff {
      rectangle "Workload Automation" as WA #lightblue {
      }
      rectangle "Event-Driven Workload" as EDW #lightblue {
      }
      rectangle "Procedural Workload" as PW #lightblue {
      }
      EDW --> WA
      PW --> WA
    }
    package Services as S #white {
      rectangle "Application" as App #lightblue {
      }
      rectangle "Complex Service" as CS #lightblue {
      }
      rectangle "Service" as Ser #lightblue {
      }
      rectangle "AI Model" as AIM #lightblue {
      }
      App "1" --> "n" CS
      App "1" --> "n" AIM
      CS "1" --> "n" Ser
    }
    WA "1" o--> "n" App
    APPI --> W
    APPI --> S
}

rectangle "Application\nDeveloper" as Dev #lightgray {
}
package "Cloud" as Cloud #lightgreen {
}

Dev --> APPI
APPI -> "Cloud"

@enduml
