@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Telemetry/Telemetry Aggregator" #lightblue {

    interface "Telemetry/Telemetry Aggregator" {
    }

    CLI ()-- "Telemetry/Telemetry Aggregator"
    REST ()-- "Telemetry/Telemetry Aggregator"
    Web ()-- "Telemetry/Telemetry Aggregator"
}

User --> "Telemetry/Telemetry Aggregator"
"Telemetry/Telemetry Aggregator" --> Used

@enduml
