@startuml
rectangle "Diagram TBD"
@enduml

partition "edgeville-manager" {

}

partition User  #cccccc {
  (*) --> "Create Project"
  --> "Write Code"
}

partition "edgeville-manager" #lightblue {
  "Write Code" --> "Test Code"
  "Test Code" --> "Deploy Code"
  "Deploy Code" --> (*)
}

partition Used  #cccccc {
}

