@startuml
Actor "actorName" as A

box "Manage-Applications" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-analytics-aggregate()
CLI -> S : analytics/aggregate()
A -> Web : analytics/aggregate()
Web -> S : analytics/aggregate()
end box

@enduml
