@startuml

salt
{
  Deploy Application and not all edge devices return regjection list
  {
      parameter1 | "value1"
      parameter2 | "value2"
      [ Cancel <&circle-x>] | [ OK <&account-login> ]
  }
}

@enduml
