@startuml
Actor "actorName" as A

box "Manage-Applications" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-model-deploy()
CLI -> S : model/deploy()
A -> Web : model/deploy()
Web -> S : model/deploy()
end box

@enduml
