@startuml

salt
{
  Peer-to-Peer communication between edge applications
  {
      parameter1 | "value1"
      parameter2 | "value2"
      [ Cancel <&circle-x>] | [ OK <&account-login> ]
  }
}

@enduml
