@startuml
Actor "actorName" as A

box "Manage-Applications" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-a-use()
CLI -> S : a/use()
A -> Web : a/use()
Web -> S : a/use()
end box

@enduml
