@startuml

package "Cloud" #ffffcc {

}

package "Physical" #ffffcc {

}

package "Control" as C #lightgray {
    interface "Control"
    package "Edgeville Agent" as EA { }
    package "Edgeville Manager" as EM { }
    package "Data Coordinator" as DC #lightblue { }
    package "Security" as S  #lightgreen {

    }
    package "Telemetry" as T #plum {
    }

    EM --> S
    EA --> S
    EM --> DC
    EA --> DC
    EM --> T
    EA --> T

    CLI ()-- "Control"
    REST ()-- "Control"
    Web ()-- "Control"
    "Control" --> EA : implemented by
    "Control" ..> EM : implemented by
}

Cloud -> C

C --> Physical

@enduml
