@startuml
Actor "actorName" as A

box "Manage-Security" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-secure-create()
CLI -> S : secure/create()
A -> Web : secure/create()
Web -> S : secure/create()
end box

@enduml
