@startuml
Actor "actorName" as A

box "Manage-Security" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-network-edge()
CLI -> S : network/edge()
A -> Web : network/edge()
Web -> S : network/edge()
end box

@enduml
