@startuml
Actor "actorName" as A

box "Manage-Cloud" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-hybrid-create()
CLI -> S : hybrid/create()
A -> Web : hybrid/create()
Web -> S : hybrid/create()
end box

@enduml
