@startuml
Actor "actorName" as A

box "Manage-Cloud" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-multi-destroy()
CLI -> S : multi/destroy()
A -> Web : multi/destroy()
Web -> S : multi/destroy()
end box

@enduml
