@startuml
Actor "actorName" as A

box "Manage-Cloud" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-multi-monitor()
CLI -> S : multi/monitor()
A -> Web : multi/monitor()
Web -> S : multi/monitor()
end box

@enduml
