@startuml
Actor "actorName" as A

box "Manage-Cloud" #lightblue
participant CLI as CLI
participant Web as Web
participant "Edgeville" as S
A -> CLI : Edgeville-edge-register()
CLI -> S : edge/register()
A -> Web : edge/register()
Web -> S : edge/register()
end box

@enduml
