@startuml
rectangle "Diagram TBD"
@enduml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Security/Detection" #lightblue {

    interface "Security/Detection" {
    }

    CLI ()-- "Security/Detection"
    REST ()-- "Security/Detection"
    Web ()-- "Security/Detection"
}

User --> "Security/Detection"
"Security/Detection" --> Used


