@startuml

package "User" #ffffcc {

}

package "Used" #ffffcc {

}

package "Security" #lightblue {

    interface "Security" {
    }

    CLI ()-- "Security"
    REST ()-- "Security"
    Web ()-- "Security"
    package Detection {
    }
    package Encryption {
    }
    package "Identity Manager" {
    }
    package "Remediation" {
    }
    package "Trust Manager" {
    }
}

User --> "Security"
"Security" --> Used

@enduml
