@startuml

  rectangle "Application Layer" as AL #lightblue {
    rectangle Analytics #white
    rectangle Services #white
    rectangle Workloads #white
  }
  rectangle "Cloud Layer" as ClL #orange {
    rectangle "Multi Cloud" as MC #white
    rectangle Cloud #white
    rectangle "Micro Cloud" as uC #white
    MC "1" --> "n" Cloud
    MC "1" --> "n" uC

  }
  rectangle "Control Layer" as CL #lightgreen {
    rectangle Security #white
    rectangle Telemetry #white
    rectangle "Data Coordination" #white

  }
  rectangle "Physical Layer" as PL #lightgray {
    rectangle Device #white
    rectangle "Edge Device" as ED #white
    rectangle "Aggregated Edge Device" as AED #white
    rectangle "Data Center" as DC #white

    ED "1" -> "n" Device
    AED "1" -> "n" ED
    AED "1" --> "n" Device
    DC "1" --> "n" ED
    DC "1" --> "n" AED

  }

 AL ---> ClL
 ClL ---> CL
 CL ---> PL

@enduml
