@startuml

rectangle "Data Center" as DC #lightgray {
  cloud "Private\nCloud" as SDI #ffccaa
  cloud "Multi\nCloud" as HC #orange
  node "Edgeville\nManager" as EM #lightgreen
}
rectangle Telco  #ffffcc {
  cloud "Private Cloud" #dddddd
  cloud "Shared\nCloud" as SC #ffccaa
}
rectangle "Edge Device" as ED1 #lightgray {
  cloud "Micro\nCloud" as uSDI #ffddcc
  node "Edgeville\nAgent" as EA1 #lightblue
}

rectangle "Aggregated Edge Device" as ED2 #lightgray {
  cloud "Micro\nCloud" as uSDI2 #ffddcc
  cloud "Multi\nCloud" as HC2 #orange
  node "Edgeville\nAgent" as EA2 #lightblue
  node "Edgeville\nManager" as EM2 #lightgreen
}

rectangle "Edge Device" as ED3 #lightgray {
  cloud "Micro\nCloud" as uSDI3 #ffddcc
  node "Edgeville\nAgent" as EA3 #lightblue
}
EM --> EA2
EM --> EA1
EM2 --> EA3
EA2 --> EM2
rectangle "IOT Gateway" as IG1 #lightyellow
rectangle "IOT Gateway" as IG2 #lightyellow
rectangle "Sensor" as D1 #lightgray
rectangle "Device" as D2 #lightgray
rectangle "Camera" as D3 #lightgray

rectangle "Device" as D4 #lightgray

IG1 -- D1
IG1 -- D2
IG1 -- D3
ED1 -- IG1
ED1 -- IG2
ED3 -- D4
HC --> SC
HC --> uSDI2
HC -> SDI
HC -> uSDI
HC2 -> uSDI2
HC2 --> uSDI3

@enduml
