@startuml

package "Control" #lightgreen {

}

package "Cloud" #lightblue {

    abstract "Cloud" {
    }


    class "Private Cloud" as PCloud
    class "mirco-Cloud" as uCloud
    class "multi-Cloud" as mCloud

    SDI ()- PCloud
    uSDI ()- uCloud
    C3 ()- mCloud
    Cloud *--> PCloud
    Cloud o--> uCloud
    Cloud o--> mCloud
}
CLI ()-- "Cloud"
REST ()-- "Cloud"
Web ()-- "Cloud"

"Cloud" --> Control

@enduml
