@startuml

partition "Cloud" {

}

partition "Operations Manager" #cccccc {
  (*) --> "Create Hybrid Cloud"
}

partition "Cloud" #lightblue {
  --> "Find Edge Devices"
}

partition Contol #cccccc {
  -> "Return Edge Devices"
}
partition "Cloud" #lightblue {
  --> "Layout Cloud Topology"
  "Layout Cloud Topology" --> "Register SDI"
  "Layout Cloud Topology" --> "Register uSDI"
  "Register SDI" --> "Hybrid Cloud Ready"
  "Register uSDI" --> "Hybrid Cloud Ready"
  --> "Monitor Cloud"
  --> "Destroy Cloud"
  --> (*)
}


@enduml
