@startuml
actor "Operations\nManager" as User

User -> "Cloud": Create Common Cloud Core
"Cloud" -> bin: multi-create()
bin -> sailsjs: multi/create()

User -> "Cloud": Monitor Multi Cloud
"Cloud" -> bin: multi-monitor()
bin -> sailsjs: multi/monitor()

User -> "Cloud": Destroy Multi Cloud
"Cloud" -> bin: multi-destroy()
bin -> sailsjs: multi/destroy()

@enduml
