@startuml
rectangle "Diagram TBD"
@enduml

package "workload" #lightblue {
    interface "workload" {

    }
    CLI ()-- "workload" : 5000
    REST ()-- "workload" : 3000
    Web ()-- "workload" : 80
}



